### PR TITLE
Add a note about `core-js` polyfilling

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

**Comment by zloirock** [comment]
ping @ljharb

Just interesting, is it simpler to regularly mark my comments as spam instead of reviewing this PR?

**Comment by ljharb** [comment]
Yep. I’m not planning on landing any changes to this proposal, including this PR, until the proposal is ready to request advancement or be withdrawn.

As you’ve seen from other similar PRs, it’s considered spam by others, too, to make frequent “ping” comments on PRs. That’s not how github works.

**Comment by zloirock** [comment]
The polyfill based on the current state of this proposal, so it not the change of this proposal and requests for advancement or withdrawal are unrelated. If you don't wanna maintain it - please, mark it as inactive in https://github.com/tc39/proposals, if not - please, review this PR. If the "maintainer" has not responded to the pull request for many months, I have every right to use "ping" and I don’t care what others think since I have the right to know about the state of this proposal since a huge number of developers experimenting with proposals depend on me.

**Comment by ljharb** [comment]
You have a right to do it, but that’s irrelevant to whether it’s considered polite.

Moreover, adding shims/polyfills/implementations to the readme is not a required part of the proposal process (especially not before stage 3), so I’m under no obligation to do so.

**Comment by zloirock** [comment]
Clear. So you do not want to add important information for users because of personal hostility and attempts to avoid competition with your own polyfills 👍 You could initially say that.

**Comment by ljharb** [comment]
Nope, that’s not it at all, but clearly i can’t change your opinion here.

**Review by ljharb — APPROVED** [review]
Since this proposal is now finally stage 2.7, and I see that [v3.37.0](https://github.com/zloirock/core-js/releases/tag/v3.37.0) of core-js includes a compliant Promise.try, I'll add this to the readme and close this PR.

**Pull request closed without merging**
